site_name: Chateauroux
theme:
  name: material
  logo : F5xJkAnWYAAG7eY.png

nav :
  - Châteauroux IP / VLAN : index.md
  - Composition du site de Châteauroux : documentation.md
  - Schéma détaillé du réseau global de Châteauroux : shemareseau.md
  - Définition d'un nom de domaine / SSH : ssh.md
  - Contrôleur de domaine : ad.md
  - Pare-Feu : parefeu.md
  - Routeur : routeur.md
  - NAT : NAT.md
  - Confs : conf.md
